package com.project.hishab.Enum;

public enum CategoryType {

    HOUSING_AND_UTILITIES,
    FOOD_AND_GROCERIES,
    TRANSPORTATION,
    PERSONAL_AND_HEALTH,
    DAILY_LIVING_AND_HOUSEHOLD,
    COMMUNICATION,
    EDUCATION_AND_SELF_DEVELOPMENT,
    ENTERTAINMENT_AND_LEISURE,
    FAMILY_AND_RELATIONSHIPS,
    SAVINGS_AND_DEBT
}
